[build]
  publish = "docs/.vitepress/dist"
  command = "yarn run docs:build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
  NODE_VERSION = "14"
